
["Client Only Settings"]
	#The list of slabs (or tags) which should not use the double variant model when two of the same slab are combined together
	#Use the wildcard value * to disable this feature for all slabs
	useDoubleSlabModelBlacklist = []
	#The list of slabs (or tags) which should not be culled when combined
	#Use the wildcard value * to disable this feature for all slabs
	slabCullBlacklist = ["#minecraft:campfires"]
	#The list of slabs (or tags) which should use the lazy model rendering technique
	#Lazy model rendering does not physically rotate the original slab model, but applies the same texture to a default vertical slab model
	#This often yields better looking results with wooden planks and does not necessarily improve the look of all vertical slabs
	#Use the wildcard value * to enable this feature for all slabs
	lazyVerticalSlabModels = ["#doubleslabs:plank_slabs"]

["Player Settings (synced with servers)"]
	#Which placement method to use to place vertical slabs
	#This is a per user option and can be any of the following values:
	#PLACE_WHEN_SNEAKING - Only place vertical slabs when you are sneaking
	#DYNAMIC - Place vertical slabs when clicking on the side of a block unless you are sneaking and place vertical slabs when sneaking when looking at the top or bottom face of a block but place regular slabs by default
	#Allowed Values: PLACE_WHEN_SNEAKING, DYNAMIC
	verticalSlabPlacementMethod = "DYNAMIC"

