
[forgeautofish]
	#Sets the delay before casting the fishing rod again (in milliseconds).
	#Range: 100 ~ 30000
	recastdelay = 1000
	#Sets the delay before reeling in the fishing rod after catching a fish (in milliseconds).
	#Range: 0 ~ 30000
	reelindelay = 0
	#Sets the default status of the Auto Fish feature
	autofish = false
	#Sets whether should the mod be turned off when the fishing rod is about to break.
	rodprotect = true
	#Does nothing currently
	autoreplace = true

	[forgeautofish.filter]
		#Toggles the entire item filter
		all = true
		#Sets item filter
		items = ["minecraft:rotten_flesh"]

