
[horse]
	#Range: > 1000
	"How many ticks it takes for a horse to give birth, 24000 = 1 Minecraft Day:" = 24000
	"Allow vanilla minecraft Horses to spawn/exist:" = false
	"Allow Genetic horses to continue to spawn/exist:" = true

[general]
	#Range: 0 ~ 100
	"How random the genes should be, 100 is all wildtype animals, 0 is completely random:" = 90
	"Allow feeding to age/grow animals:" = false
	"Animals will spawn with random biome type" = false
	#Set this to true to enable omnigenders, meaning the gender of the animal is irrelevant to who can fall pregnant, lay eggs, milk or sire young. False results in gendered animals. Visually nothing changes.
	"Allow Omnigenders:" = false
	#Allowed Values: RAVENOUS, MORE_HUNGRY, STANDARD, LESS_HUNGRY, NEVER_HUNGRY
	"How fast the animals get hungry, Values: RAVENOUS, MORE_HUNGRY, STANDARD, LESS_HUNGRY, NEVER_HUNGRY" = "STANDARD"
	"Animal inventory tabs will be on the top instead of side:" = true

[llama]
	#Range: > 1000
	"How many ticks it takes for a Llama to give birth, 24000 = 1 Minecraft Day:" = 48000
	"Allow vanilla minecraft Llamas to spawn/exist:" = false
	"Allow Genetic Llamas to continue to spawn/exist:" = true

	[llama."How highly llama spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 4

	[llama."The minimum number of llamas you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[llama."The maximum number of llamas you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

[chicken]
	"Allow vanilla minecraft Chickens to spawn/exist:" = false
	"Allow Genetic Chickens to continue to spawn/exist:" = true

	[chicken."How highly chicken spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 10

	[chicken."The minimum number of chickens you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 4

	[chicken."The maximum number of chickens you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 4

[rabbit]
	"Allow vanilla minecraft Rabbits to spawn/exist:" = false
	"Allow Genetic Rabbits to continue to spawn/exist:" = true
	#Range: > 1000
	"How many ticks it takes for a rabbit to give birth, 24000 = 1 Minecraft Day:" = 24000

	[rabbit."How highly rabbit spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 4

	[rabbit."The minimum number of rabbits you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[rabbit."The maximum number of rabbits you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

[cow]
	"Allow vanilla minecraft Mooshrooms to spawn/exist:" = false
	#Range: > 1000
	"How many ticks it takes for a Cow to give birth, 24000 = 1 Minecraft Day:" = 48000
	"Allow Genetic Cows to continue to spawn/exist:" = true
	"Allow vanilla minecraft Cows to spawn/exist:" = false
	"Allow Genetic Mooshrooms to continue to spawn/exist:" = true
	"Allow Genetic Mooblooms to replace Mooblooms added by other mods" = false

	[cow."How highly cow spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 8

	[cow."The minimum number of cows you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 4

	[cow."The maximum number of cows you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 4

	[cow."How highly mooshroom spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 8

	[cow."The minimum number of mooshrooms you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 4

	[cow."The maximum number of mooshrooms you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 4

[sheep]
	"Allow vanilla minecraft Sheep to spawn/exist:" = false
	#Range: > 1000
	"How many ticks it takes for a Rabbit to give birth, 24000 = 1 Minecraft Day:" = 48000
	"Allow Genetic Sheep to continue to spawn/exist:" = true

	[sheep."How highly sheep spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 12

	[sheep."The minimum number of sheep you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 4

	[sheep."The maximum number of sheep you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 4

[pig]
	#Range: > 1000
	"How many ticks it takes for a Pig to give birth, 24000 = 1 Minecraft Day:" = 48000
	"Allow vanilla minecraft Pigs to spawn/exist:" = false
	"Allow Genetic Pigs to continue to spawn/exist:" = true

	[pig."How highly pig spawning is weighted, larger numbers spawn more"]
		#Range: 1 ~ 20
		" Default is 6" = 6

	[pig."The minimum number of pigs you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 2" = 2

	[pig."The maximum number of pigs you want to find in a group at spawn"]
		#Range: 1 ~ 60
		" Default is 3" = 3

