
#Bit detection
[BitDetection]
	#Set to true to make itlt yell at people attempting to use 32x java for the modpack.
	ShouldYellAt32BitUsers = true
	#If ShouldYellAt32BitUsers is set to true, this is the message that will be displayed to the user.
	Message = "You are using a 32 bit version of java. This is not recommended with this modpack. Or any, for that matter."

#Display
[Display]
	#Change this value to change the name of the MineCraft window
	windowDisplayTitle = "SorbetCraft 2 v6.0b"
	#Set to true to load a custom icon from config\itlt\icon.png
	loadCustomIcon = false
	#Set to true to attempt to use the icon assigned to the modpack by the technic launcher. 
	#This will take priority over loadCustomIcon
	useTechnicIcon = false
	#Set to true to attempt to get the display name of the pack of the info json file \nThis will take priority over windowDisplayTitle
	useTechnicDisplayName = false

#Management of a dedicated server
[Server]
	#Set to true to have a dedicated server added to the server list ingame. The server will not overwrite others servers.
	AddDedicatedServer = true
	#The name of the dedicated server to add.
	ServerName = "The Sorbet"
	#The ip of the dedicated server to add.
	ServerIP = "play.sorbet.tk"

