
[general]
	#In minute
	#Range: > 1
	timer = 30
	#Dynamicaly detect the world name ?
	dynamic = true
	#If dynamicWorldName == false, select the world name
	worldname = "world"
	#Number files to keep
	#Range: > 1
	fileToKeep = 15
	#Enable auto-backup
	enable = true
	#Enable backup at the server start
	backupOnStart = true
	#Max weight of the openbackup folder in MB
	#Range: > 1024
	maxSizeBackupFolder = 30720

[messages]
	msgBackupStarted = "[OpenBackup] Server backup - Started"
	msgBackupDone = "[OpenBackup] Server backup - Done"
	msgUnzip = "[OpenBackup] The backup is unziped in openbackups/restore"
	#Enable the message's broadcast when the backup start/done. 1 - ALL, 2 - OP, 3- NONE
	#Range: 1 ~ 3
	broadcast = 1

