
#General settings
[general]
	#Diameter of appearance of the flower around the hive
	#Range: 1 ~ 30
	diameter = 10
	#Chance to have a flower appear when the bee has delivered its honey
	#Range: 0.0 ~ 1.0
	chance = 0.5

