
["Save locations"]
	#Where to save the panoramas
	panoramaSaveFolder = "./panoramas"

["Main menu"]
	#Whether to show the flash warning screen on launch. 
	disableFlashWarning = true
	#Whether to use custom panoramas on the main menu
	useCustomPanoramas = true

