
#Limits for chunk loading
[chunkLoadingLimits]
	#The number of tickets a player can be assigned instead of a mod. This is shared across all mods.
	#Range: > 0
	maximumPlayerTickets = 500
	#Range: 0 ~ 225
	maximumChunksPerTicket = 25
	#Maximum ticket count for the mod. Zero disables chunkloading capabilities.
	#Range: > 0
	maximumModTickets = 200

